<?php

function bu_components_theme($existing, $type, $theme, $path) {
  return array(
    'bu_collapsible_block' => array(
      'variables' => array(
        'title' => '',
        'items' => array(),
      )
    ),
    'bu_news_and_events_block' => array(
      'variables' => array(
        'title' => '',
        'items' => array(),
      )
    ),
    'bu_square_button_arrow' => array(
      'variables' => array(
        'link_url' => '',
        'link_text' => '',
        'text_above' => '',
        'text_below' => '',
        'color' => 'red',
      ),
    ),
    'bu_expanded_rounded_button_arrow' => array(
      'variables' => array(
        'link_url' => '',
        'link_text' => '',
        'plus_sign' => FALSE,
      ),
    ),
    'bu__items' => array(
      'variables' => array(
        'title' => '',
        'items' => array(),
        'bottom_link_url' => '',
        'bottom_link_text' => '',
        'title_color' => 'blue',
        'is_floating' => FALSE,
      ),
    ),
    'bu_simple_items_block_with_background' => array(
      'variables' => array(
        'title' => '',
        'items' => array(),
        'is_floating' => FALSE,
        'background_color' => 'red'
      ),
    ),
    'bu_subsections_lateral_menu' => array(
      'variables' => array(
        'items' => array(),
        'is_floating' => FALSE,
      ),
    ),
  );
}
