display:
  default:
    display_options:
      footer:
        area:
          content:
            value: "<p><a class=\"link-red\" href=\"/en/newsletters\">See all newsletters </a></p>\r\n"
            format: full_html
  block_1:
    display_options:
      title: 'LEGAL BULLETIN'
