display:
  outstanding_block_2:
    display_options:
      footer:
        area:
          content:
            value: "<p><a class=\"outstanding-items-bottom-text link-red\" href=\"/noticias\">See all the news\r\n</a></p>\r\n"
            format: full_html
